### ISSUE TITLE
Sporočilo v commitu za 2. domačo nalogo

### ISSUE THREAD

**Issue by katjabercic** [Janudi05/racunalniski-praktikum#1]
Za točko pri 2. domači nalogi mora v repozitoriju biti commit s sporočilom `2. domača naloga`, v vašem repozitoriju pa je samo commit s sporočilom `2. domaca naloga`. Če želite dobiti točko, je najlažje, če naredite še eno spremembo README datoteke, ki jo zabeležite s sporočilom `2. domača naloga`.

**Comment by Janudi05** [comment]
Najlepša hvala za komentar. Lp Jan Udir
